version: '3.8'

services:
  delivery_backend:
    container_name: delivery_backend
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    deploy:
      mode: replicated
      replicas: 1

  db:
    container_name: 'delivery_backend_db'
    image: 'postgres:14.0-alpine'
    ports:
      - '5432:5432'
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=delivery_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ../db-data/postgres/:/var/lib/postgresql/data/
