version: '3.8'

services:
  delivery_backend:
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    ports:
      - '8080:8080'
    deploy:
      mode: replicated
      replicas: 1